// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDo335-25AfgrK6miVrvlFzZRp1hD_pFrs',
    appId: '1:427838240918:web:97c5eb99d65dde4e28eab7',
    messagingSenderId: '427838240918',
    projectId: 'chat-app-91d1b',
    authDomain: 'chat-app-91d1b.firebaseapp.com',
    storageBucket: 'chat-app-91d1b.appspot.com',
    measurementId: 'G-SBETJNG0HS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw0LYZy5DIfM1NswwPHqBhAdhbuNLjHNc',
    appId: '1:427838240918:android:755e5717a8226deb28eab7',
    messagingSenderId: '427838240918',
    projectId: 'chat-app-91d1b',
    storageBucket: 'chat-app-91d1b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBGRhU-bvUrieiA1G_vnCbKrhPA0X5KYE',
    appId: '1:427838240918:ios:65bda65557e20af228eab7',
    messagingSenderId: '427838240918',
    projectId: 'chat-app-91d1b',
    storageBucket: 'chat-app-91d1b.appspot.com',
    iosClientId: '427838240918-uhvofiiu3jnnh4kqc1cecqfmr3n3smrs.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
